spring:
  application:
    name: msvc-gateway-server
  cloud:
    gateway:
      routes:
        - id: msvc-auth
          uri: http://localhost:9100
          predicates:
            - Path=/api/auth/**
        - id: msvc-user
          uri: http://localhost:8001
          predicates:
            - Path=/api/user/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9100

server:
  port: 9000

# Eureka Config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
