spring:
  application:
    name: msvc-gateway-server
  cloud:
    gateway:
      routes:
        - id: msvc-auth
          uri: lb://msvc-auth
          predicates:
            - Path=/api/auth/**
        - id: msvc-user
          uri: lb://msvc-user
          predicates:
            - Path=/api/user/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9100

springdoc:
  swagger-ui:
    urls:
      - name: Usuarios
        url: http://msvc-user/v3/api-docs
      - name: Autenticación
        url: http://msvc-auth/v3/api-docs

server:
  port: 9000

# Eureka Config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
