server:
  port: 8001

# Base de datos
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipes_ia
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
